# Generated by Django 5.2 on 2025-07-04 08:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_categorie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FA',
            fields=[
                ('id_fa', models.AutoField(primary_key=True, serialize=False)),
                ('prenom_fa', models.CharField(blank=True, max_length=100, null=True)),
                ('commune_fa', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone_fa', models.CharField(blank=True, max_length=20, null=True)),
                ('email_fa', models.CharField(blank=True, max_length=100, null=True)),
                ('libelle_reseausociaux', models.CharField(blank=True, max_length=100, null=True)),
                ('libelle_veterinaire', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('id_provenance', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_provenance', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sexe',
            fields=[
                ('id_sexe', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_sexe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id_statut', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_statut', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nom_animal', models.CharField(max_length=100)),
                ('date_arrivee', models.DateField(blank=True, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('num_identification', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('primo_vacc', models.DateField(blank=True, null=True)),
                ('rappel_vacc', models.DateField(blank=True, null=True)),
                ('vermifuge', models.DateField(blank=True, null=True)),
                ('antipuce', models.DateField(blank=True, null=True)),
                ('sterilise', models.BooleanField(blank=True, default=False, null=True)),
                ('biberonnage', models.BooleanField(blank=True, default=False, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categorie')),
                ('fa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fa')),
                ('provenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.provenance')),
                ('sexe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sexe')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.statut')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='animaux/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('animal_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='api.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nom_animal', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('num_identification', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('primo_vacc', models.DateField(blank=True, null=True)),
                ('rappel_vacc', models.DateField(blank=True, null=True)),
                ('vermifuge', models.DateField(blank=True, null=True)),
                ('antipuce', models.DateField(blank=True, null=True)),
                ('sterilise', models.BooleanField(blank=True, default=False, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categorie')),
                ('fa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fa')),
                ('provenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.provenance')),
                ('sexe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sexe')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.statut')),
            ],
        ),
    ]
